class PhysicEventNames {

    static REGISTER_COLLIDER = 'REGISTER_COLLIDER';
    static UNREGISTER_COLLIDER = 'UNREGISTER_COLLIDER';

    static ON_COLLISION_ENTER = 'ON_COLLISION_ENTER';

    static ON_COLLISION_STAY = 'ON_COLLISION_STAY';

    static ON_COLLISION_EXIT = 'ON_COLLISION_EXIT';
}